# ls-lint configuration for config-generator
# See: https://ls-lint.org/2.x/configuration/the-basics.html
# RULE: Everything is snake_case except conventional config files

ls:
  # TypeScript source files - snake_case
  src/**/*.ts: snake_case
  src/**/*.js: snake_case
  
  # Config files at root - conventional names
  ./*.config.{js,mjs,ts,json}: snake_case | regex:^(commitlint|lint-staged)\.config\.(js|mjs|ts)$
  ./*.{json,yml,yaml,lock}: snake_case | regex:^(package|tsconfig|biome|turbo|bunfig|bun\.lockb)\.
  
  # Test files - allow .spec.ts pattern
  tests/**/*.{ts,js}: snake_case | regex:^.*\.spec\.(ts|js)$
  
  # CSV config files - lowercase with hyphens
  config/**/*.csv: lowercase | regex:^[a-z0-9\-]+\.csv$
  
  # Directories - snake_case
  src/**/: snake_case
  config/**/: snake_case
  tests/**/: snake_case
  .github/**/: snake_case | regex:^\.github$

ignore:
  - node_modules
  - dist
  - .git
  - .husky/_
  - .devcontainer
  - .idea
  - coverage
  - out
  - build