// Auto-generated configuration exports
// This file is generated by scripts/compile-config.ts
// Do not edit manually

export type { Items } from "./generated/items";
export { items, getItemsById } from "./generated/items";
export type { GameSettingsConfig } from "./generated/game-settings";
export { gameSettingsConfig } from "./generated/game-settings";
export type { Heroes } from "./generated/heroes";
export { heroes, getHeroesById } from "./generated/heroes";
