// Auto-generated configuration exports
// This file is generated by scripts/compile-config.ts
// Do not edit manually

export { GameSettingsConfig, gameSettingsConfig } from "./generated/game-settings";
export { Heroes, heroes, getHeroesById } from "./generated/heroes";
export { Items, items, getItemsById } from "./generated/items";
