// Auto-generated configuration exports
// This file is generated by scripts/compile-config.ts
// Do not edit manually

export type { Calculator } from "./generated/calculator";
export { calculator } from "./generated/calculator";
export type { Economy } from "./generated/economy";
export { economy } from "./generated/economy";
export type { StatusEffects } from "./generated/status-effects";
export { statusEffects } from "./generated/status-effects";
